sudo: true
language: python
dist: bionic

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      sudo: true
    - env: TOXENV=flake8

install:
    - pip install tox==2.9.1

before_script: |
    sudo apt update -y
    sudo apt install --only-upgrade docker-ce -y

script:
    - tox
